# Generated by Django 4.0.7 on 2022-09-10 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('card_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name_of_family_head', models.CharField(max_length=60)),
                ('son_of', models.CharField(max_length=60)),
                ('livingfrom', models.IntegerField()),
                ('address', models.CharField(max_length=60)),
                ('ward_or_houseno', models.CharField(max_length=10)),
                ('landmark', models.CharField(blank=True, choices=[('Talikulam', 'Talikulam'), ('Pallimukk', 'Pallimukk'), ('Puthiyangady', 'Puthiyangady'), ('KunnathPally', 'Kunnathpally'), ('Nambikadavu', 'Nambikadavu'), ('Aynichod', 'Aynichod'), ('BhagavanNagar', 'Bhagavannagar'), ('Naseeb', 'Naseeb'), ('Kakkerivalavu', 'Kakkerivalavu'), ('Kaithakal', 'Kaithakal'), ('Aryampadam', 'Aryampadam'), ('Ravinagar', 'Ravinagar'), ('AsadNagar', 'Asadnagar'), ('College', 'College'), ('Fathahpalli', 'Fathahpalli')], max_length=60)),
                ('post_office', models.CharField(choices=[('Talikulam', 'Talikulam'), ('Nattika', 'Nattika')], default='Talikulam', max_length=60)),
                ('panchayath', models.CharField(choices=[('Talikulam', 'Talikulam'), ('Nattika', 'Nattika')], default='Talikulam', max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('education', models.CharField(blank=True, max_length=60, null=True)),
                ('job', models.CharField(blank=True, max_length=60, null=True)),
                ('bloodgroup', models.CharField(choices=[('NA', 'Na'), ('A+', 'A+'), ('O+', 'O+'), ('B+', 'B+'), ('AB+', 'Ab+'), ('A-', 'A-'), ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'Ab-')], default='NA', max_length=60)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('H', 'Family Head'), ('M', 'Member'), ('W', 'Wife'), ('M', 'Mother'), ('S', 'Son'), ('D', 'Daughter'), ('F', 'Father'), ('O', 'Son in Law'), ('A', 'Daughter in Law')], default='M', max_length=5)),
                ('Required_help_for_marriage', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
                ('Required_help_for_building_home', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
                ('Required_any_other_financial_help', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.family')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.ward'),
        ),
    ]
