# Generated by Django 3.2 on 2022-12-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_member_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='card_number',
            new_name='mahallu_house_no',
        ),
        migrations.RemoveField(
            model_name='family',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='family',
            name='ward_or_houseno',
        ),
        migrations.AddField(
            model_name='family',
            name='mahallu_ward',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='pachayath_ward',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='panchayath_house_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
