# Generated by Django 3.2 on 2022-12-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20221222_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='mahallu_house_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='family',
            name='panchayath_house_no',
            field=models.CharField(max_length=10),
        ),
    ]
