# Generated by Django 3.2 on 2022-12-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20221222_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='family',
            name='landmark',
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('H', 'Family Head'), ('AL', 'Auncle'), ('AY', 'Aunty'), ('BL', 'Brother in Law'), ('D', 'Daughter'), ('DL', 'Daughter in Law'), ('F', 'Father'), ('GD', 'Grand Daughter'), ('GF', 'Grand Father'), ('GM', 'Grand Mother'), ('GS', 'Grand Son'), ('M', 'Mother'), ('MR', 'Member'), ('S', 'Son'), ('SL', 'Son in Law'), ('SS', 'Sister in Law'), ('W', 'Wife')], default='M', max_length=5),
        ),
    ]
