# Generated by Django 3.2 on 2022-12-23 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_locality_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='area',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.locality'),
        ),
    ]
