# Generated by Django 3.2 on 2022-12-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_family_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='financial_status',
            field=models.CharField(choices=[('UP', 'Upper Class'), ('UM', 'Upper Middle Class'), ('MC', 'Middle Class'), ('LM', 'Lower Middle Class'), ('LC', 'Lower Class'), ('VP', 'Very Poor')], default='MC', max_length=5),
        ),
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='income',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='marrital_satatus',
            field=models.CharField(choices=[('M', 'Married'), ('S', 'Single'), ('D', 'Divorced'), ('WM', 'Widower'), ('W', 'Widow')], default='S', max_length=5),
        ),
        migrations.AddField(
            model_name='member',
            name='religeous_education',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='panchayath',
            field=models.CharField(choices=[('Thalikulam', 'Thalikulam'), ('Nattika', 'Nattika')], default='Thalikkulam', max_length=60),
        ),
        migrations.AlterField(
            model_name='family',
            name='post_office',
            field=models.CharField(choices=[('Thalikulam', 'Thalikulam'), ('Nattika', 'Nattika')], default='Thalikkulam', max_length=60),
        ),
    ]
