# Generated by Django 3.2 on 2022-12-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20221223_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='previous_mahallu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='remarks',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
