# Generated by Django 3.2 on 2022-12-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20221223_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
